polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('', 
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

vdb/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vdb.views.home', name='home'),
    # url(r'^vdb/', include('vdb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^admin/', include(admin.site.urls)),

)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here

class company(models.Model):
	name = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date_published')
    
	def __unicode__(self):
		return self.name
	
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		was_published_recently.admin_order_field = 'pub_date'
		was_published_recently.boolean = True
		was_published_recently.short_description = 'Published recently'
 
	description = models.CharField(max_length=1000, widget=models.Textarea)
	internalPOV = models.CharField(max_length=1000)
    	externalPOV = models.CharField(max_length=1000)
    

polls/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.views import generic
from django.shortcuts import render, get_object_or_404

from polls.models import company 

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_vendor_list'

	def get_queryset(self):
		return Vendor.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = company
	template_name = 'polls/detail.html'

polls/templates/polls/detail.html
<h1>{{ company.name }} </h1>
<h2>{{ company.description }} </h2>

{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

polls/templates/polls/index.html
{% if latest_vendor_list %}
	<ul>
	{% for vendor in latest_vendor_list %}
		<li><a href="{% url 'polls:detail' company.id %}">{{ company.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No vendors are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1> {{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>